" This isn't the vimrc file that we care about, .vimrc should be the name and
" located elsewhere
" Dont be vim compatible
set nocompatible
source ~/dotfiles/vim/plugins.vimrc
source ~/dotfiles/vim/mappings.vimrc
source ~/dotfiles/vim/editor.vimrc
source ~/dotfiles/vim/graphical.vimrc
source ~/dotfiles/vim/search.vimrc
" set cin aw ai is ts=4 sw=4 tm=50 nu noeb bg=dark cul hlsearch
